name: Deploy my Lambda Function

# trigger on all push events to main branch
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
upload:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: download artifacts
       uses: actions/download-artifact@v2
       with:
        name: zipped-bundle
     - name: configure aws CLI
       uses: aws-actions/configure-aws-credentials@v1
       with: 
        aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
        aws-access-secret-key : ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: us-east-1
     - name: upload artifacts to s3
       run: aws s3 cp ${{ github.sha }}.zip s3://jayasriawsbucket/${{ github.sha }}
    
     
